name: apple-clang++

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  BUILD_TYPE: Debug
  
jobs:
  build:
    runs-on: macos-14
    name: ci-macos-14-apple-clang-18-static
    env:
      CLANG18_PATH: /opt/homebrew/opt/llvm@18/bin/clang

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Install clang
        run: |
          brew install llvm@18 \
          && echo 'export PATH="/opt/homebrew/opt/llvm@18/bin:$PATH"' >> /Users/runner/.bash_profile \
          && source /Users/runner/.bash_profile \
          && which clang++
