name: apple-clang++

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Install llvm
        run: |
          brew install llvm@16
          echo 'export PATH="/usr/local/opt/llvm@16/bin:$PATH"' >> $HOME/.zshrc
          echo 'export LDFLAGS="-L/usr/local/opt/llvm@16/lib"' >> $HOME/.zshrc
          echo 'export CPPFLAGS="-I/usr/local/opt/llvm@16/include"' >> $HOME/.zshrc
          source $HOME/.zshrc

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -DCMAKE_CXX_COMPILER=$(which clang++)

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -- -Wno-sign-conversion
        
      - name: Run Tests
        working-directory: build/
        run: ./config-cxx-UT
